### ISSUE TITLE
Indy: Update the Ambassador Helm chart to support NLB

### ISSUE THREAD

**Issue by juraj-durech** [hyperledger-labs/blockchain-automation-framework#121]
The Ambassador Helm chart should for aws and aws-baremetal expose the Indy nodes via a TCP NLB with a fixed IP address. All ports used by Indy nodes in the particular org have to be exposed (example below).

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-080a6a3311715645e"
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  ambassador
      config:
        use_proxy_proto: true
        use_remote_address: false
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - name: indy-node1-node
    port: 9711
    targetPort: 9711
  - name: indy-node1-client
    port: 9712
    targetPort: 9712
  - name: indy-node2-node
    port: 9721
    targetPort: 9721
  - name: indy-node2-client
    port: 9722
    targetPort: 9722
  - name: indy-node3-node
    port: 9731
    targetPort: 9731
  - name: indy-node3-client
    port: 9732
    targetPort: 9732
  - name: indy-node4-node
    port: 9741
    targetPort: 9741
  - name: indy-node4-client
    port: 9742
    targetPort: 9742
  selector:
    service: ambassador
```

The Helm chart

https://github.com/hyperledger-labs/blockchain-automation-framework/tree/develop/platforms/shared/charts/ambassador

and respective Ansible roles have to be modified.
