### ISSUE TITLE
Feature to associate the chaincode with respect to the channel

### ISSUE THREAD

**Issue by KarthikSamaganam550** [hyperledger-labs/blockchain-automation-framework#1251]
### Description:

I would like to associate the chaincode with respect to the channel.

### Proposal summary: 

would like to associate the chaincode with respect to the channel. And the proposal network.yaml would be like this

### network.yaml 

```

network:
  chaincodes:
    - chaincode1: 
        ........
    - chaincode2:
        ........    
    - chaincode3:
        ........
  organizations:
    - organization:
      name: <name of the org1>
      services:
        peers:
          - peer:
            name: peer0  
            chaincodes:
              - name: <Name of the chaincode>
                version : <version of the chaincode> 
                installed: true | false  # default value is false         
              - name: <Name of the chaincode>
                version : <version of the chaincode>
                installed: true | false  # default value is false 
          - peer:
            name: peer2
            chaincodes:
              - name: <Name of the chaincode>
                version : <version of the chaincode> 
                installed: true | false  # default value is false         
              - name: <Name of the chaincode>
                version : <version of the chaincode> 
                installed: true | false  # default value is false
    - organization:
      name: <name of the org2>
      services:
        peers:
          - peer:
            name: peer0
            chaincodes:
              - name: <Name of the chaincode>
                version : <version of the chaincode> 
                installed: true | false  # default value is false         
              - name: <Name of the chaincode>
                version : <version of the chaincode> 
                installed: true | false  # default value is false
          - peer:
            name: peer2
            chaincodes:
              - name: <Name of the chaincode>
                version : <version of the chaincode>  
                installed: true | false  # default value is false        
              - name: <Name of the chaincode>
                version : <version of the chaincode> 
                installed: true | false  # default value is false
      - organization:
        name: <name of the org3>
        services:
          peers:
            - peer:
              name: peer0
              chaincodes:
                - name: <Name of the chaincode>
                  version : <version of the chaincode>  
                  installed: true | false  # default value is false        
                - name: <Name of the chaincode>
                  version : <version of the chaincode> 
                  installed: true | false  # default value is false
            - peer:
              name: peer2
              chaincodes:
                - name: <Name of the chaincode>
                  version : <version of the chaincode>  
                  installed: true | false  # default value is false        
                - name: <Name of the chaincode>
                  version : <version of the chaincode>  
                  installed: true | false  # default value is false          
  channels:
    - channel:
      channel_name: <channel name1>
      chaincode: 
         - name: <chaincode name>
           version: <version of the chaincode>
         - name: <chaincode name>
           version: <version of the chaincode>
      participants:
        - organization:
          name: <name of the org 1>
          peers:
            - peer:
              name: peer0
            - peer:
              name: peer1
        - organization:
          name: <name of the org 2>
          peers:
            - peer:
              name: peer0
            - peer:
              name: peer1 
    - channel:
      channel_name: <channel name2>
      chaincode: 
         - name: <chaincode name>
           version: <version of the chaincode>
         - name: <chaincode name>
           version: <version of the chaincode>      
      participants:
        - organization:
          name: <name of the org 2>
          peers:
            - peer:
              name: peer0
            - peer:
              name: peer1
        - organization:
          name: <name of the org 3>
          peers:
            - peer:
              name: peer0
            - peer:
              name: peer1                             
```
