### ISSUE TITLE
While adding new org in Indy extra ConfigMaps are being generated

### ISSUE THREAD

**Issue by sauveergoel** [hyperledger-labs/blockchain-automation-framework#1291]
**Describe the bug**
While adding new org in Indy extra ConfigMaps are being generated corresponding to pool and genesis configmaps for that org. This is happening because the condition in the ansible-playbook i.e. `/platforms/hyperledger-indy/configration/deploy-network.yaml` , is getting true for the configmap generation role: 
```
  # Create and deploy domain genesis
  - name: 'Create domain genesis'
    include_role:
      name: setup/domain_genesis
    when: network['type'] == 'indy' and (network.genesis.add_org is not defined or network.genesis.add_org)

  # Create and deploy pool genesis
  - name: 'Create pool genesis'
    include_role:
      name: setup/pool_genesis
    when: network['type'] == 'indy' and (network.genesis.add_org is not defined or network.genesis.add_org)
```

The flag condition could be updated to**network.genesis.add_org == false** instead of **network.genesis.add_org** such that when the add_org is true it does not create the extra resources.

**Expected behavior**
Pool and Domain Genesis should not be generated for the added organization. They should only be comprised of details from the organizations present at the time of network generation
