### ISSUE TITLE
Unnecessary expectation from BAF admin to fill in cert information under `orderers`

### ISSUE THREAD

**Issue by arsulegai** [hyperledger-labs/blockchain-automation-framework#1310]
### Description
I cannot categorize this to be bug, so user story was closely matching available option. This appears to be an unnecessary requirement for an administrator. When composing the deployment file (ex: `network.yaml`), there is a section for adding orderers and under which there is an expectation to put in orderer URI, orderer cert information/path.

Given that certs are stored in Vault (including any private keys), one can expect the orderer certs to be present in Vault in a pre-configured directory structure. It allows administrator to be free from having to specify a path where they are stored.

```yaml
    orderers:
      - orderer:
        certificate:  # Path to orderer certificate. For inital network setup, ensure that the directory is present, the file need not be present. For adding a new organization, ensure that the file is the crt file of the orderer of the existing network.
      - orderer:
```

The filling in of certificate can be done by BAF itself if the Vault path is known or prefixed. Avoids user to manually copy required certificates for each ordering service node in a given directory.

### Acceptance Criteria
1. Remove any dependency on having to specify a path for storing orderer nodes certificate.
2. Remove any dependency on having to copy any files manually.
