### ISSUE TITLE
Addition of annotations for pods/components supplied via `network.yaml` - Fabric

### ISSUE THREAD

**Issue by arsulegai** [hyperledger-labs/blockchain-automation-framework#1422]
**Is your feature request related to a problem? Please describe.**
Kubernetes components rely on annotations to perform additional tasks. For example, HAPROXY uses annotations to identify the sub-path where the server can play a proxy role. Similarly these annotations can be used on core blockchain components to manage the way they behave.

**Describe the solution you'd like**
An option to supply annotations from the input `network.yaml` and apply it on the deployed components. Pass them via the HelmRelease.

**Describe alternatives you've considered**
Post deployment of BAF, identify the resources and annotate the resources.

**Additional context**
NA

**Comment by alvaropicazo** [comment]
Hi @arsulegai , just to know, which type annotations are you expecting to have? I think the solution could be adding an annotation section in the network.yaml and specify them there. Will be working on this in the next days

**Comment by arsulegai** [comment]
Hi @alvaropicazo,

I was thinking of making this a generic feature, to give flexibility for somebody to add their own annotations. These annotations can be supplied from `network.yaml` as an input. Here is an example that I was considering

**Possibility 1:**
```
network:
  env: dev
  annotations-enabled: true
  ...

# applicable when the network setup is requested.
# user shall specify that custom annotations are enabled at the network level.
annotations:
  peers:
     peer1.example.org:
       - annotation-key1:value1
       - annotation-key2:value2
     peer2.example.org:
       - annotation-key1:value1
   orderers:
     orderer1.orderer-org.com:
       - annotation-key1:value1
   ca:
...
```

**Possibility 2:**
Pass the annotations as part of the current structure, within each organization where we pass peers information, orderers information, CA's information.

Any of these approaches is good to have. This feature will enable, the network setup through BAF to interoperate with advanced features for production management on K8s.
