### ISSUE TITLE
authority-authority-trustee-auth-job failing while initiating Indy network on BAF

### ISSUE THREAD

**Issue by vaibhavmittal215** [hyperledger-labs/blockchain-automation-framework#1470]
I am trying to run a Hyperledger_indy network using steps given at various doc links (steps explained below).
The error that I am facing is:
![command-3](https://user-images.githubusercontent.com/79312374/118895366-a6e5bd00-b923-11eb-9056-0cc98a6ddba0.png)
It keeps on retrying and then exits.
To analyze the error, I added some debug statements in the indy-auth-job [file](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/master/platforms/hyperledger-indy/charts/indy-auth-job/templates/job.yaml). The file now looks like:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $.Values.metadata.name }}"
  namespace: "{{ $.Values.metadata.namespace }}"
spec:
  template:
    metadata:
      labels:
        app: "{{ $.Values.metadata.name }}"
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: "{{ $.Values.image.pullSecret }}"
      serviceAccountName: {{ $.Values.account.admin_service }}
      containers:
        - name:  "{{ $.Values.image.name }}"
          image: "{{ $.Values.image.repository }}"
          imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
            - >
              apk update && apk add curl git jq;
              echo "1";
              curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.1/bin/linux/amd64/kubectl;
              echo "2";
              chmod u+x kubectl && mv kubectl /bin/kubectl;
              echo "3";

              validateVaultResponse () {
               if [ ${1} != 200 -a ${1} != 204 ]; then
                echo "ERROR: Unable to retrieve. Http status: ${1}"
                exit 1
                fi
               };

              print () {
                echo ${1} = ${2};
              };

              export KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
              print "KUBE_TOKEN" ${KUBE_TOKEN};
              echo "4";

              export KUBE_CERT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt);
              print "KUBE_CERT" ${KUBE_CERT};
              echo "5";

              export VAULT_SA_NAME=$(kubectl get sa {{ $.Values.account.service }} -n {{ $.Values.metadata.namespace }} -o jsonpath="{.secrets[*]['name']}");
              print "VAULT_SA_NAME" ${VAULT_SA_NAME};
              echo "6";

              export SA_JWT_TOKEN=$(kubectl get secret $VAULT_SA_NAME -n {{ $.Values.metadata.namespace }} -o jsonpath="{.data.token}" | base64 -d; echo);
              print "SA_JWT_TOKEN" ${SA_JWT_TOKEN};
              echo "7";

              SA_JWT_TOKEN="$(curl --request POST --data '{"jwt": "'"$KUBE_TOKEN"'", "role": "{{ $.Values.account.admin_role }}"}' -s -k {{ $.Values.vault.address }}/v1/auth/{{ $.Values.vault.admin_auth_path }}/login | jq -r '.auth.client_token')";
              print "SA_JWT_TOKEN" ${SA_JWT_TOKEN};
              echo "8";

              export SA_CA_CRT_ONELINE=$(kubectl get secret $VAULT_SA_NAME -n {{ $.Values.metadata.namespace }} -o jsonpath="{.data['ca\.crt']}" | base64 -d | awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}');
              print "SA_CA_CRT_ONELINE" ${SA_CA_CRT_ONELINE};
              echo "9";

              # Create auth

              curl --header "X-Vault-Token: $VAULT_TOKEN" --request POST --data '{"type": "kubernetes"}' {{ $.Values.vault.address }}/v1/sys/auth/{{ $.Values.vault.auth_path }};

              curl --header "X-Vault-Token: $VAULT_TOKEN" --request POST --data '{"kubernetes_host": "{{ $.Values.network.kubernetes_url }}", "kubernetes_ca_cert": "'"$SA_CA_CRT_ONELINE"'", "token_reviewer_jwt": "'"$SA_JWT_TOKEN"'"}' -s -k {{ $.Values.vault.address }}/v1/auth/{{ $.Values.vault.auth_path }}/config;

              # Check auth

              response_status=$(curl -s -o /dev/null -w "%{http_code}" --header "X-Vault-Token: $VAULT_TOKEN" {{ $.Values.vault.address }}/v1/auth/{{ $.Values.vault.auth_path }}/config);

              validateVaultResponse ${response_status};
              echo "10";
              # Create policy

              curl  --header "X-Vault-Token: $VAULT_TOKEN" --request PUT --data '{"policy": "{{ $.Values.vault.policy_content }}"}' {{ $.Values.vault.address }}/v1/sys/policy/{{ $.Values.vault.policy }};

              # Check policy

              response_status=$(curl -s -o /dev/null -w "%{http_code}" --header "X-Vault-Token: $VAULT_TOKEN" {{ $.Values.vault.address }}/v1/sys/policy/{{ $.Values.vault.policy }});

              validateVaultResponse ${response_status};
              echo "11";
              # Create role

              curl -s -o /dev/null -w "%{http_code}" --header "X-Vault-Token: $VAULT_TOKEN" --request POST --data '{"bound_service_account_names": "{{ $.Values.account.service }}","bound_service_account_namespaces": "{{ $.Values.metadata.namespace }}","policies": ["{{ $.Values.vault.policy }}"], "ttl": 3600}' {{ $.Values.vault.address }}/v1/auth/{{ $.Values.vault.auth_path }}/role/{{ $.Values.account.role }};

              # Check role

              response_status=$(curl -s -o /dev/null -w "%{http_code}" --header "X-Vault-Token: $VAULT_TOKEN" {{ $.Values.vault.address }}/v1/auth/{{ $.Values.vault.auth_path }}/role/{{ $.Values.account.role }});

              validateVaultResponse ${response_status};
              echo "12";

```
The output of the above file is:
![command-2](https://user-images.githubusercontent.com/79312374/118895800-7baf9d80-b924-11eb-8bfc-76e4d1ea6838.png)

These are the outputs of some of the commands:
![command-1](https://user-images.githubusercontent.com/79312374/118895875-a26dd400-b924-11eb-898d-9d4167f10170.png)
![command-4](https://user-images.githubusercontent.com/79312374/118895883-a6015b00-b924-11eb-8cb9-6ad248146fee.png)

Below I have written all the steps that I followed to create the network. 
Assuming, we will be running the BAF on a docker container where the host machine is ubuntu 18.04. 

## Step 1

First of all, we need to install the dependencies required for running the BAF. Follow the steps given in this link relevant to ubuntu system https://blockchain-automation-framework.readthedocs.io/en/develop/developer/dev_prereq.html.

### Git set-up
1. Install git on your system and check if the git is working properly.
```
git --version
```
2. Set up git using https://blockchain-automation-framework.readthedocs.io/en/develop/developer/dev_prereq.html#setting-up-git-on-your-machine
```
git config --global user.name "<username>"
git config --global user.email "<useremail>"
```
3. Verify the username and password
```
git config user.name
git config user.email
```
4. Make a folder project in your home directory and fork the git repo https://github.com/hyperledger-labs/blockchain-automation-framework inside that folder
```
cd
mkdir project
cd project
git clone git@github.com:<githubuser>/blockchain-automation-framework.git
cd blockchain-automation-framework
mkdir build
```
5. Setup a new branch 'local' in that repo
```
cd ~/project/blockchain-automation-framework
git checkout -b local
git push --set-upstream origin local
```
6. Set up the ssh keys for github
```
ssh-keygen -q -N "" -f ~/.ssh/gitops
``` 
This generates an SSH key-pair in your ~/.ssh directory: gitops (private key) and gitops.pub (public key). Add the public key contents from gitops.pub (starts with ssh-rsa) as an Access Key (with read-write permissions) in your Github repository by following [this guide](https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account). After that run the below commands
```
eval "$(ssh-agent)"
ssh-add ~/.ssh/gitops
```

### Docker set-up
Installed docker on my machine and created an account on the docker hub.

### Vault set-up
We will be running the vault inside an EC2 machine.

1. Make an EC2 machine and ssh into the machine. Configurated the network to allow all kinds of connection requests.
2. Install the vault on the EC2 machine using this link https://www.vaultproject.io/downloads.
3. Check if the vault command is running by just typing `vault`.
4. Make a project directory and export the vault address on the command line
```
mkdir project
cd project
export VAULT_ADDR='http://<Vault EC2 IP address>:8200'
```
5. Make the config file for vault and run the vault. Make a file named config.hcl at path ~/project and put the below code into that file
```
ui = true
storage "file" {
   path    = "/home/ubuntu/project/data"
}
listener "tcp" {
   address     = "0.0.0.0:8200"
   tls_disable = 1
}
api_addr = "http://0.0.0.0:8200"
disable_mlock = true
```
After creating the file, run this command
```
vault server -config=config.hcl
```
6. Open a browser and goto `http://<Vault EC2 IP address>:8200`, enter 1 into both the fill ups and press enter. In the next screen, download the keys and `continue to unseal`. You will find the key and root_token in the downloaded json file. Keep them safe and also use those to unseal the vault.
7. Leave that terminal and browser tab as it is (don't close them). Open a new terminal and ssh into the same EC2 instance. Run the following command to create a secret 
```
mkdir project
cd project
export VAULT_ADDR='http://<Vault EC2 IP address>:8200'
export VAULT_TOKEN="<root_token from json file>"
vault secrets enable -version=1 -path=secret kv
```
## Step 2
We now need to create a kubernetes cluster. We will be making a cluster on EKS (Elastic Kubernetes service) provided by AWS. A basic video link for EKS on youtube is here https://www.youtube.com/watch?v=p6xDCz00TxU.
1. We need to have eksctl installed on our machine which is a command line utility for interaction with AWS servers regarding eks services. Install eksctl: 
```
curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp\nsudo mv /tmp/eksctl /usr/local/bin
eksctl version
```
2. Now to create the cluster we need to have aws credentials stored in our system. For that. first we need to have awscli installed:
```
sudo apt-get install awscli
```
then run
```
aws configure
```
It will ask for token and key which we can get from the users page in aws console. For now we are using root credentials so that we have every permission.

3. Now we will create the eks cluster. It will take only a single command to create the cluster:
```
eksctl create cluster \ 
--name test-cluster \
--version 1.19 \
--region ap-south-1 \
--nodegroup-name linux-nodes \
--node-type t3.medium \
--nodes 1
```
This command will create a cluster named test-cluster with kubernetes version 1.19, ec2 instance type t3.medium, number of nodes 1 and the region specified ap-south-1 which is the Mumbai region. It will take some time for the cluster to start.
## Step 3
Writing the network.yaml file. We will be using the sample file provided by official BAF team. The file is here https://github.com/hyperledger-labs/blockchain-automation-framework/blob/master/platforms/hyperledger-indy/configuration/samples/network-indyv3.yaml. Name this file network.yaml and store it in the ~/project/blockchain-automation-framework/build directory. The file looks like this, only change the fields with <>:
```
---
# This is a sample configuration file for hyperledger indy which can reused for a sample indy network of 9 nodes.
# It has 3 organizations:
# 1. organization "authority" with 1 trustee
# 2. organization "provider" with 1 trustee, 2 stewards and 1 endorser
# 3. organization "partner" with 1 trustee, 2 stewards and 1 endorser

network:
  type: indy
  version: 1.11.0

  env:
    type: "dev"
    proxy: ambassador
    ambassadorPorts: 15010,15023,15024,15033,15034,15043,15044
    loadBalancerSourceRanges: 
    retry_count: 50
    external_dns: enabled

  docker:
    url: "index.docker.io/hyperledgerlabs"
    username: "<docker_username>"
    password: "<docker_password>"

  name: baf 

  genesis:
    state: absent
    pool: genesis/pool_transactions_genesis
    domain: domain/domain_transactions_genesis

  organizations:
    - organization:
      name: authority
      type: peer
      external_url_suffix: indy.blockchaincloudpoc.com
      cloud_provider: aws

      aws:
        access_key: "<aws_access_key>"
        secret_key: "<aws_secret_key>"
        zone: "<Cluster Node EC2 zone>"               # example : "ap-south-1a"
        region: "ap-south-1"

        publicIps: ["<Cluster Node EC2 IP>"]        # example : ["13.233.138.106"]

      k8s:
        config_file: "/home/blockchain-automation-framework/build/config"
        context: "<kube context>" # example : "vaibhavmi@test-cluster.ap-south-1.eksctl.io"

      vault:
        url: "http://<Vault EC2 IP address>:8200"
        root_token: "<root_token from json file>"
        secret_path: "secret"

      gitops:
        git_protocol: "https"
        git_url: "https://github.com/<git_username>/blockchain-automation-framework.git"
        branch: "local"
        release_dir: "platforms/hyperledger-indy/releases/dev"
        chart_source: "platforms/hyperledger-indy/charts"
        git_repo: "github.com/<git_username>/blockchain-automation-framework.git"
        username: "<git_username>"
        password: "<git_password>"
        email: "<git_email>"
        private_key: "/home/blockchain-automation-framework/build/gitops"

      services:
        trustees:
        - trustee:
          name: authority-trustee
          genesis: true
          server:
            port: 8000
            ambassador: 15010

    - organization:
      name: provider
      type: peer
      cloud_provider: aws
      external_url_suffix: indy.blockchaincloudpoc.com

      aws:
        access_key: "<aws_access_key>"
        secret_key: "<aws_secret_key>"
        zone: "<Cluster Node EC2 zone>"
        region: "ap-south-1"

      publicIps: ["<Cluster Node EC2 IP>"]

      k8s:
        config_file: "/home/blockchain-automation-framework/build/config"
        context: "<kube context>"

      vault:
        url: "http://<Vault EC2 IP address>:8200"
        root_token: "<root_token from json file>"
        secret_path: "secret"

      gitops:
        git_protocol: "https"
        git_url: "https://github.com/<git_username>/blockchain-automation-framework.git"
        branch: "local"
        release_dir: "platforms/hyperledger-indy/releases/dev"
        chart_source: "platforms/hyperledger-indy/charts"
        git_repo: "github.com/<git_username>/blockchain-automation-framework.git"
        username: "<git_username>"
        password: "<git_password>"
        email: "<git_email>"
        private_key: "/home/blockchain-automation-framework/build/gitops"

      services:
        trustees:
        - trustee:
          name: provider-trustee
          genesis: true
        stewards:
        - steward:
          name: provider-steward-1
          type: VALIDATOR
          genesis: true
          publicIp: <Cluster Node EC2 IP>
          node:
            port: 9711
            targetPort: 9711
            ambassador: 9711
          client:
            port: 9712
            targetPort: 9712
            ambassador: 9712
        - steward:
          name: provider-steward-2
          type: VALIDATOR
          genesis: true
          publicIp: <Cluster Node EC2 IP>
          node:
            port: 9721
            targetPort: 9721
            ambassador: 9721
          client:
            port: 9722
            targetPort: 9722
            ambassador: 9722
        endorsers:
        - endorser:
          name: provider-endorser
          full_name: Some Decentralized Identity Mobile Services Provider
          avatar: http://provider.com/avatar.png
          server:
            httpPort: 15023
            apiPort: 15024

    - organization:
      name: partner
      type: peer
      cloud_provider: aws
      external_url_suffix: indy.blockchaincloudpoc.com

      aws:
        access_key: "<aws_access_key>"
        secret_key: "<aws_secret_key>"
        zone: "<Cluster Node EC2 zone>"
        region: "ap-south-1"

      publicIps: ["<Cluster Node EC2 IP>"]

      k8s:
        config_file: "/home/blockchain-automation-framework/build/config"
        context: "<kube context>"

      vault:
        url: "http://<Vault EC2 IP address>:8200"
        root_token: "<root_token from json file>"
        secret_path: "secret"

      gitops:
        git_protocol: "https"
        git_url: "https://github.com/<git_username>/blockchain-automation-framework.git"
        branch: "local"
        release_dir: "platforms/hyperledger-indy/releases/dev"
        chart_source: "platforms/hyperledger-indy/charts"
        git_repo: "github.com/<git_username>/blockchain-automation-framework.git"
        username: "<git_username>"
        password: "<git_password>"
        email: "<git_email>"
        private_key: "/home/blockchain-automation-framework/build/gitops"

      services:
        trustees:
        - trustee:
          name: partner-trustee
          genesis: true
        stewards:
        - steward:
          name: partner-steward-1
          type: VALIDATOR
          genesis: true
          publicIp: <Cluster Node EC2 IP>
          node:
            port: 9731
            targetPort: 9731
            ambassador: 9731
          client:
            port: 9732
            targetPort: 9732
            ambassador: 9732
        - steward:
          name: partner-steward-2
          type: VALIDATOR
          genesis: true
          publicIp: <Cluster Node EC2 IP>
          node:
            port: 9741
            targetPort: 9741
            ambassador: 9741
          client:
            port: 9742
            targetPort: 9742
            ambassador: 9742
        endorsers:
        - endorser:
          name: partner-endorser
          full_name: Some Decentralized Identity Mobile Services Partner
          avatar: http://partner.com/avatar.png
          server:
            httpPort: 15033
            apiPort: 15034
```

## Step (extra)
To resolve a python error, I had to change a job file https://github.com/hyperledger-labs/blockchain-automation-framework/blob/master/platforms/shared/configuration/roles/setup/aws-cli/tasks/main.yaml. The change is highlighted in the image:
![alt text](https://github.com/vaibhavmittal215/baf/blob/master/python_change.png?raw=true)

Also, we need to copy some files into build directory:
```
cp ~/.ssh/gitops ~/project/blockchain-automation-framework/build
cp ~/.kube/config ~/project/blockchain-automation-framework/build
```

## Step 4
The final step is to create the docker image and run a docker container which will run the BAF:
```
cd ~/project/blockchain-automation-framework
docker build . -t hyperledgerlabs/baf-build
docker run -it -v $(pwd):/home/blockchain-automation-framework/ hyperledgerlabs/baf-build
```

To me it looks like there is some issue with the vault, but I am not able to tell what exactly. Can you tell me if the steps that I have followed are right to create the Indy network?
