### ISSUE TITLE
Use hashi_vault lookup plugin

### ISSUE THREAD

**Issue by Henni** [hyperledger-labs/blockchain-automation-framework#367]
### Description
As a developer I want to follow Ansible best practices so that I can guarantee code quality and utilise all features of Ansible.

Currently whenever Vault is accessed from Ansible roles, the shell command is used.
Instead it would be best practice to stay in the declarative style of Ansible playbooks and utilize the community lookup plugin hashi_vault, when a secret is pulled from Vault.

Reading a secret could then be implemented with a simple copy command instead:
```yaml
- copy:
  content: "{{ lookup('hashi_vault', 'secret=secret/hello:value token=VAULT_TOKEN url=VAULT_ADDR')}}"
  dest: /path/to/destination/file
```

[Example in our Code Base (Hyperledger Fabric Peer Crypto Creation)](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/master/platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/main.yaml#L29)

[Ansible Doc for hashi_vault](https://docs.ansible.com/ansible/latest/plugins/lookup/hashi_vault.html)

### Acceptance Criteria
1. No `vault kv get` call is wrapped inside an Ansible shell command
