### ISSUE TITLE
Duplicate Helmreleases

### ISSUE THREAD

**Issue by Henni** [hyperledger-labs/blockchain-automation-framework#392]
**Describe the bug**
Some pods / jobs are not deployed and the playbook aborts after waiting for them to come up.

**To Reproduce**
1. Run Hyperledger Fabric deployment
2. Abort execution during pod deployments
3. Reset network
4. Rerun deployment

**Expected behavior**
The playbook should continue to run. Instead I have to delete the helmreleases manually so that Flux redeploys them properly.

**Logs**

_Flux Helm Operator_
```
ts=2020-02-24T10:48:40.307915435Z caller=chartsync.go:374 component=chartsync warning="release 'supplychain-orderer2' does not belong to HelmRelease, this may be an indication that multiple HelmReleases with the same release name exist" resource=supplychain-net:helmrelease/supplychain-orderer2
```
_HelmRelease Status_
```
status:
  conditions:
  - lastTransitionTime: "2020-02-24T10:35:39Z"
    lastUpdateTime: "2020-02-24T10:48:39Z"
    message: successfully cloned git repo
    reason: GitRepoCloned
    status: "True"
    type: ChartFetched
  - lastTransitionTime: "2020-02-24T10:35:41Z"
    lastUpdateTime: "2020-02-24T10:48:40Z"
    message: release 'supplychain-orderer2' does not belong to HelmRelease
    reason: HelmUpgradeFailed
    status: "False"
    type: Released
  observedGeneration: 1
  releaseName: supplychain-orderer2
  releaseStatus: DEPLOYED
  valuesChecksum: ""
```
