### ISSUE TITLE
Indy: Change trustees and stewards to a list

### ISSUE THREAD

**Issue by juraj-durech** [hyperledger-labs/blockchain-automation-framework#74]
Change the network.yaml and Vault structure to a list of trustees and stewards.

Example:

```
      services:
        trustees:
        - trustee:
          name: authority-trustee
```
